services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: ../.env
        required: false
    environment:
      PORT: "3000"
